name: Release
on:
  push:
    tags:
      - "v*" # Push events to matchign v*, i.e. v1.0, v20.15.0

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance

    steps:
      - id: checkout-step
        name: Checkout code
        uses: actions/checkout@v4

      - id: setup-node-step
        name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - id: install-dependencies-step
        name: Install dependencies
        run: npm clean-install

      - id: build-step
        name: Build package
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: npm run build

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
